name: Mend CLI Container Scan

on:
  workflow_dispatch

jobs:
  mend-cli:
    name: Mend-CLI
    env:
      MEND_EMAIL: ${{secrets.MEND_EMAIL}}
      MEND_USER_KEY: ${{secrets.MEND_USERKEY}}
      MEND_URL: https://saas.whitesourcesoftware.com
    runs-on: ubuntu-latest
    steps:
      # test
      - name: test secret
        run: | 
          echo ${{secrets.MEND_EMAIL}}

      # Downloading Mend CLI
      - name: Mend CLI
        run: | 
          echo Downloading Mend CLI
          curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          echo Start Mend Container scan
          mend image ubuntu:latest